### ISSUE TITLE
[DOC - 02] Adicionar Template do Documento de Visão

### ISSUE THREAD

**Issue by aleronupe** [translate-me/translate-me#2]
### Descrição:
Essa issue tem como objetivo adicionar o template do Documento de Visão ao projeto no GitHub e à pasta do projeto no Drive.

### Critérios de aceitação

- [ ] Template Editável do Documento de Visão no GitHub
- [ ] Template Editável do Documento de Visão no Drive

### Tarefas

- [ ] Encontrar template do Documento de Visão que vá de encontro com o necessário para o projeto
- [ ] Adicionar template na pasta docs/templates no repositório do GitHub
- [ ] Adicionar template na pasta Documentos/Templates no Drive

**Comment by gabibguedes** [comment]
Porque q tem q ter o template em varios lugares?

**Comment by gabibguedes** [comment]
não é melhor deixar em um só pra n confundir?

**Comment by gabibguedes** [comment]
@aleronupe

**Comment by aleronupe** [comment]
Pensei em deixar o template no github pra ter o registro e termos ele no drive como orientação a medida que formos gerando nossa própria versão do documento, por quê lá só nós temos acesso.

**Comment by gabibguedes** [comment]
@aleronupe Pode ser, ai depois que terminarmos no drive, atualiza o do git. To mais preocupada com o markdown, vai ser em markdown neh?

**Comment by gabibguedes** [comment]
Acho melhor deixar na wiki...

**Comment by gabibguedes** [comment]
Ta na pasta docs do drive e na wiki, link:
https://github.com/desenho2019-1/traducao/wiki/Documento-de-Visão
