### ISSUE TITLE
[ORG - 05] Organizar Github Pages

### ISSUE THREAD

**Issue by aleronupe** [translate-me/translate-me#20]
### Descrição
Essa issue promove a organização do GitHub Pages do Projeto, com a documentação de artefatos e a modularização de temas 

### Critérios de aceitação

- [x] GitHub Pages com index modularizado por temas
- [x] Padronização de Páginas

### Tarefas

- [x] Documentação das Reuniões (Scrum)
- [x] Documentação das Modelagens Bizzagi
- [x] Documentação dos Modelos UML
- [ ] Organização dos Requisitos
- [x] Organização dos Métodos de Elicitação

**Comment by gabibguedes** [comment]
Adicionar documentação de branches e commits
