### ISSUE TITLE
[DOC - 03] Adicionar Template da Folha de Estilo

### ISSUE THREAD

**Issue by aleronupe** [translate-me/translate-me#3]
### Descrição:
Essa issue tem como objetivo adicionar o template da Folha de Estilo ao projeto no GitHub e para edição no Drive

### Critérios de aceitação

- [ ] Template Editável da Folha de Estilo no GitHub
- [ ] Template Editável do Folha de Estilo no Drive
- [x] Template deve contemplar estilo de Commits
- [x] Template deve contemplar estilo de Issues
- [x] Template deve contemplar estilo de Pull Requests
- [x] Template deve contemplar estilos de programação para Python

### Tarefas

- [ ] Encontrar template do Folha de Estilo que vá de encontro com o necessário para o projeto
- [ ] Adicionar template na pasta docs/templates no repositório do GitHub
- [ ] Adicionar template na pasta Documentos/Templates no Drive

**Comment by davialvb** [comment]
* Os templates de issue e PR foram adicionados na pasta defalt ".github" para que sejam carregados ao criar uma issue ou um PR. 
* As politicas de commit e branchs estão na pasta "docs".
* O guia de estilo para python foi criado a partir do PEP 8. Então o documento porta somente as coisas que foram julgadas mais importante para um bom codigo em python. Posteriormente se houver alguma duvida quando a forma de codigo limpo deve-se olhar em [PEP8](https://www.python.org/dev/peps/pep-0008/)
