### ISSUE TITLE
[Frontend] US05 - Criar primeira versão da homepage

### ISSUE THREAD

**Issue by luizguilherme5** [translate-me/translate-me#34]
## Descrição
Deve ser criada uma primeira versão da página inicial da aplicação, que será para onde será redirecionada assim que um usuário realizar o login ou se cadastrar. A página deve ter um enfoque no usuário que busca submeter um texto a ser traduzido, mostrando as categorias de textos disponíveis, cards que possuem os itens a serem traduzidos, um cabeçalho (navbar), um menu lateral quando o site for acessado pelo smartphone ou em telas menores, um espaço para visitar o perfil, um botão para 'venha traduzir conosco', a logo da aplicação e um footer com um espaço para informações gerais e termos de uso.

## Critérios de aceitação

- [ ] ~Deve ser a página que a autenticação redirecionada~
- [x] Deve conter um espaço para o usuário
- [x] Deve conter um cabeçalho com logo, botão de perfil, botão para sair, botão de alternar a visualização para tradutores
- [x] Deve conter um footer com informações gerais e termos de uso

**Comment by helenagoulart** [comment]
Algumas alterações foram feitas na identidade visual, uma vez que as cores e alguns ícones não estavam harmonizando entre si. Além disso, o primeiro critério de aceitação não pode ser concluído uma vez que a tela de login ainda não foi concluída.

**Comment by gabibguedes** [comment]
O redirecionamento do login para a homepage deve ser feito na página de login
