### ISSUE TITLE
Issue teste

### ISSUE THREAD

**Issue by luizguilherme5** [translate-me/translate-me#37]
## Critérios de aceitação

- [ ] Login realizado de forma segura
- [ ] Página de login contém: "Esqueci minha senha!"
- [ ] etc ...

**Comment by luizguilherme5** [comment]
Comentário teste

**Comment by luizguilherme5** [comment]
Comentário 2

**Comment by luizguilherme5** [comment]
Comentário 3

**Comment by luizguilherme5** [comment]
Comentário 4

**Comment by aleronupe** [comment]
@luizguilherme5 Comentário aleatório
