### ISSUE TITLE
[DOC - 10] Refactor Static UMLs Artifacts 

### ISSUE THREAD

**Issue by aleronupe** [translate-me/translate-me#41]
## Description

This issues defines the aspects of the UML Artifacts to be refactored.

## Acceptance Criteria 

- [ ] Search for Static UMLs documents and articles
- [ ] Add introduction to .md file of the Static UMLs
- [ ] Describe each category of the Static UML artifacts (Classes, Packages and Components)
- [ ] Add version to each of the artifacts
- [ ] Add references to the .md file

**Comment by gabibguedes** [comment]
The PR from this issue has already been closed, can we close this issue?
