### ISSUE TITLE
TS02 - Add linter pep8

### ISSUE THREAD

**Issue by victorhdcoelho** [translate-me/translate-me#67]
## Description
Add linter on your text editor to improve your development. The linter is to indicate some criteria's pep8 in your code.
## Acceptance criteria 
- [ ] Work on your text editor

**Comment by aleronupe** [comment]
@victorhdcoelho @luizguilherme5 @joaorobson @renan601 @mbslet @helenagoulart @RomuloSouza @gabibguedes @davialvb @aleronupe
