### ISSUE TITLE
[ORG - 02] Implementar Deploy autmático do Github Pages

### ISSUE THREAD

**Issue by aleronupe** [translate-me/translate-me#8]
### Descrição:

Essa issue busca a implementação de um sistema para **deploy** do conteúdo adicionado aos arquivos **markdown** no github pages do repositório **docs**

### Critérios de aceitação

- [ ] Atualização da página do github pages automaticamente após **commit**
- [ ] Automatização do comando **mkdocs gh-deploy**

### Tarefas

- [x] Pesquisa da forma de implementação do deploy contínuo do **mkdocs**
- [x] Implementação do **deploy** conforme ferramenta CI necessária
- [x] Teste do **deploy** automatizado

**Comment by luizguilherme5** [comment]
Deploy automatizado realizado com sucesso, disponível em:
https://travis-ci.org/desenho2019-1/docs
